# Android - Minimo
android.useAndroidX=true
android.enableJetifier=false
android.suppressUnsupportedCompileSdk=35

# Compilacion: MINIMO
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.jvmargs=-Xmx1024m -Xms512m
org.gradle.daemon=false
org.gradle.workers.max=1

# Sin optimizaciones
org.gradle.build.cache.enabled=false
